const GUESTNA_PHONE = "+966 54 753 4666";
const GUESTNA_PHONE_RAW = "+966547534666";
const GUESTNA_PHONE_DIGITS = "966547534666";

export const CONSTANT_VALUES = {
  GUESTNA_PHONE,
  GUESTNA_PHONE_RAW,
  GUESTNA_PHONE_DIGITS,
  WHATSAPP_CONTACT: `https://api.whatsapp.com/send?phone=${GUESTNA_PHONE_DIGITS}`,
  MIN_BUDGET: 50,
  MAX_BUDGET: 5000,
  PER_PAGE: 15,
  TABLE_PER_PAGE: 5,
  PACKAGE: "PACKAGE",
  ACTIVITY: "ACTIVITY",
  HALF_DAY: "HALF_DAY",
  USER_ID: "user_id",
  AUTH_TOKEN: "auth_token",
  PROFILE_IMAGE: "profile_image",
  SELECTED_ORGANIZATIONS: "selected_organizations",
  LONG_TIME_SAVING_TOKEN: 30,
  SHORT_TIME_SAVING_TOKEN: 1,

  PAYMENT_METHODS: {
    CREDIT_CARD: "CREDITCARD",
    STC: "STCPAY",
    TAMARA: "TAMARA",
    APPLE: "APPLE",
  },

  SENDING_OTP_OPTIONS: {
    EMAIL: "EMAIL",
    SMS: "SMS",
    WHATSAPP: "WHATSAPP",
  },

  URLS: {
    VERCEL_URL: process.env.NEXT_PUBLIC_B2C_VERCEL,
    B2B_VERCEL_URL: process.env.NEXT_PUBLIC_B2B_VERCEL,
  },

  USERS: {
    VISITOR: "VISITOR",
    PARENT: "PARENT",
  },

  MAIN_CATEGORIES: {
    ENTERTAINMENT_CENTERS: "ENTERTAINMENT_CENTERS",
    RIYADH_VIBES: "RIYADH_VIBES",
    OUTSIDE_RIYADH: "OUTSIDE_RIYADH",
  },

  GENDERS: {
    MALE: "MALE",
    FEMALE: "FEMALE",
    BOTH: "BOTH",
  },
};
