export const CUSTOMIZATION_ACTIONS = {
  INITIATE: "INITIATE",
  CHANGE_BOOKING_DAY: "CHANGE_BOOKING_DAY",
  ADD_NEW_TRIP: "ADD_NEW_TRIP",
  REPLACE_TRIP: "REPLACE_TRIP",
  REMOVE_TRIP: "REMOVE_TRIP",
  CHANGE_TRIP_DAY: "CHANGE_TRIP_DAY",
  CHANGE_TRIP_TIME_RANGE: "CHANGE_TRIP_TIME_RANGE",
  CHANGE_SERVICES_TRIP: "CHANGE_SERVICES_TRIP",
  CHANGE_TARGET_AUDIENCES: "CHANGE_TARGERAUDINENCES",
  ADD_DAY: "ADD_DAY",
};
