export const ONBOARDING_DOCUMENT_TYPES = {
  COMMERCIAL_REGISTRATION: "COMMERCIAL_REGISTRATION",
  TAX_CERTIFICATE: "TAX_CERTIFICATE",
  NATIONAL_ADDRESS: "NATIONAL_ADDRESS",
  OTHER: "OTHER",
};

export default ONBOARDING_DOCUMENT_TYPES;
