export const PROVIDER_ORDER_STATUS = {
  PENDING_PROVIDER_APPROVAL: "PENDING_PROVIDER_APPROVAL",
  PENDING: "PENDING",
  SCHEDULED: "SCHEDULED",
  ON_HOLD: "ON_HOLD",
  DONE: "DONE",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  PENDING_COMPANY_APPROVAL: "PENDING_COMPANY_APPROVAL",
  PENDING_CLIENT_REVIEW: "PENDING_CLIENT_REVIEW",
};

export default PROVIDER_ORDER_STATUS;
