export const SORTING_TYPE = {
  HIGHEST_SELLING: "HIGHEST_SELLING",
  NEWEST: "NEWEST",
  OLDEST: "OLDEST",
  LOWEST_PRICE: "LOWEST_EFFECTIVE_PRICE",
  HIGHEST_PRICE: "HIGHEST_EFFECTIVE_PRICE",
  HIGHEST_LOVER: "HIGHEST_LOVER",
  HIGHEST_RATE: "HIGHEST_RATE",
};
