export const TRIP_STATUS = {
  ALL: "ALL",
  SCHEDULED: "SCHEDULED",
  PENDING: "PENDING",
  CANCELLED: "CANCELLED",
  CANCLED: "CANCLED",
  ENDED: "ENDED",
  PENDING_COMPANY_APPROVAL: "PENDING_COMPANY_APPROVAL", // Pending approval - Company
  APPROVED: "APPROVED", // Approved - After approval by the Company
  REJECTED: "REJECTED",
  ON_HOLD: "ON_HOLD",
  DONE: "DONE",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  REFUNDED: "REFUNDED",
  PENDING_CLIENT_REVIEW: "PENDING_CLIENT_REVIEW",
};
