export const USERS = {
  VISITOR: "VISITOR",
  B2B_PARENT: "B2B_PARENT",
  B2B_ADMINISTRATION: "B2B_ADMINISTRATION",
  B2B_STAFF_MANAGER: "B2B_STAFF_MANAGER",
  B2B_STAFF_FINANCE: "B2B_STAFF_FINANCE",
  B2B_STAFF_STMS: "B2B_STAFF_STMS",
};
