const theme = {
  ltr: "ltr",
  rtl: "rtl",
  placeholder: "editor-placeholder",
  paragraph: "mb-2 relative",
  hr: "border-t border-gray-300 my-4",
  quote: "border-l-4 border-gray-300 pl-4 italic text-gray-600 my-2",
  heading: {
    h1: "text-3xl font-bold mb-4",
    h2: "text-2xl font-bold mb-3",
    h3: "text-xl font-bold mb-2",
  },
  list: {
    nested: {
      listitem: "list-none",
    },
    ol: "list-decimal ml-6 mb-2",
    ul: "list-disc ml-6 mb-2",
    listitem: "mb-1",
  },
  link: "text-mainColor underline hover:text-opacity-80 transition-colors cursor-pointer",
  code: "bg-gray-100 font-mono text-sm px-1 rounded",
  codeHighlight: {
    atrule: "text-blue-600",
    attr: "text-blue-600",
    boolean: "text-red-500",
    builtin: "text-green-600",
    cdata: "text-gray-500",
    char: "text-green-600",
    class: "text-blue-600",
    "class-name": "text-blue-600",
    comment: "text-gray-500 italic",
    constant: "text-blue-600",
    deleted: "text-red-500",
    doctype: "text-gray-500",
    entity: "text-blue-600",
    function: "text-blue-600",
    important: "text-blue-600",
    inserted: "text-green-600",
    keyword: "text-purple-600",
    namespace: "text-blue-600",
    number: "text-red-500",
    operator: "text-blue-600",
    prolog: "text-gray-500",
    property: "text-blue-600",
    punctuation: "text-gray-600",
    regex: "text-orange-500",
    selector: "text-green-600",
    string: "text-green-600",
    symbol: "text-blue-600",
    tag: "text-blue-600",
    url: "text-blue-600",
    variable: "text-blue-600",
  },
  table:
    "border-collapse border-spacing-0 overflow-y-scroll w-max my-4 border border-gray-300",
  tableRow: "border border-gray-300",
  tableCell: "border border-gray-300 p-2 min-w-[75px] align-top text-left",
  tableCellHeader: "bg-gray-100 font-bold",
  text: {
    bold: "font-bold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
  },
};

export default theme;
