// This file was generated by the Sentry wizard because we couldn't find a root layout file.
// Modified to prevent hydration errors - the actual layout is in [locale]/layout.jsx
import * as Sentry from '@sentry/nextjs';


export function generateMetadata() {
  return {
    other: {
      ...Sentry.getTraceData(),
    }
  }
};

export default function RootLayout({
  children,
}) {
  // Don't render html/body here - let [locale]/layout.jsx handle it
  return children;
}
